[build]
  command = "npm run build"
  publish = "out"

[build.environment]
  NODE_VERSION = "18"
  # Note: Add your actual Stripe API keys in the Netlify Dashboard Environment Variables section
  # Do not put actual API keys in this file as they would be exposed in version control

# For static export, we don't need the Next.js Netlify plugin
# [[plugins]]
#   package = "@netlify/plugin-nextjs"

# These redirects ensure that client-side routing works correctly
[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200
  status = 200

# This ensures that client-side routing works
[[redirects]]
  from = "/*"
  to = "/.netlify/functions/nextjs-server"
  status = 200
