[build]
  command = "npm run build"
  publish = "out"

[build.environment]
  NODE_VERSION = "18"
  # Note: Add your actual Stripe API keys in the Netlify Dashboard Environment Variables section
  # Do not put actual API keys in this file as they would be exposed in version control

# For Single Page Applications (SPA) - handle client-side routing
[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200

# API routes - if you have any
[[redirects]]
  from = "/api/*"
  to = "/.netlify/functions/:splat"
  status = 200
