[build]
  command = "npm run build"
  publish = ".next"

[[plugins]]
  package = "@netlify/plugin-nextjs"

[build.environment]
  NODE_VERSION = "18"

# Enable Next.js server-side rendering mode
[functions]
  included_files = [".next/static/**"]

# These redirects ensure that client-side routing works correctly
[[redirects]]
  from = "/_next/static/*"
  to = "/_next/static/:splat"
  status = 200

[[redirects]]
  from = "/_next/data/*"
  to = "/_next/data/:splat"
  status = 200

[[redirects]]
  from = "/api/*"
  to = "/.netlify/functions/nextjs-server/api/:splat"
  status = 200

# This ensures that client-side routing works
[[redirects]]
  from = "/*"
  to = "/.netlify/functions/nextjs-server"
  status = 200
